name: nextjs-prisma-vercel-debug

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    shm_size: 512mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev_owner
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: devdb
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--dbname",
          "neondb",
          "--username",
          "neondb_owner",
        ]
      start_period: 20s
      start_interval: 1s
    logging:
      driver: local
      options:
        max-size: 20m
        max-file: 5
